Merge: G2P + Wikipron

In [1]:
import pandas as pd

g2p = pd.read_csv('g2p-wiktionary-11-2-2020.tsv', sep='\t', names=['writing', 'phonetic'])
g2p = g2p.apply(lambda col: col.str.replace(' ', '', regex=False))
g2p['count'] = g2p['writing'].map(g2p['writing'].value_counts())
g2p

            writing                phonetic  count
0                 ก                    kɔː˧      1
1                ก.                    kɔː˧      1
2              ก.ค.              kɔː˧.kʰɔː˧      1
3            ก.ท.ม.         kɔː˧.tʰɔː˧.mɔː˧      1
4              ก.พ.              kɔː˧.pʰɔː˧      1
...             ...                     ...    ...
14478          ไฮโซ               haj˧.soː˧      1
14479  ไฮโดรคาร์บอน  haj˧.droː˧.kʰaː˧.bɔn˥˩      1
14480      ไฮโดรเจน      haj˧.droː˧.t͡ɕeːn˧      2
14481      ไฮโดรเจน      haj˧.droː˧.t͡ɕen˥˩      2
14482           ไฮ้                   haj˦˥      1

[14483 rows x 3 columns]

In [2]:
wikipron = pd.read_csv('thai_wikipron_5-4-2026.csv')
wikipron

         writing            phonetic  count
0              ก                kɔː˧      2
1              ก          kɔː˧.kaj˨˩      2
2             ก.                kɔː˧      1
3           ก.ค.          kɔː˧.kʰɔː˧      1
4         ก.ท.ม.     kɔː˧.tʰɔː˧.mɔː˧      1
...          ...                 ...    ...
18305   ไฮโดรเจน  haj˧.droː˧.t͡ɕeːn˧      2
18306   ไฮโดรเจน  haj˧.droː˧.t͡ɕen˥˩      2
18307        ไฮ้               haj˦˥      1
18308  …ใด…หนึ่ง      ….daj˧.….nɯŋ˨˩      1
18309     …ไป…ไป       ….paj˧.….paj˧      1

[18310 rows x 3 columns]

In [24]:
g2p[~g2p['writing'].isin(wikipron['writing'])]

,writing,phonetic,count
327,กรุงเฮก,kruŋ˧.hek̚˦˥,1
1136,การ์บูเวดี,kaː˧.buː˧.weː˧.diː˧,1
1686,ข้าเจ้า,kʰaː˥˩.t͡ɕaw˥˩,1
1703,คฑากร,kʰa˦˥.tʰaː˧.kɔːn˧,1
1730,คทากร,kʰa˦˥.tʰaː˧.kɔːn˧,1
1885,ควอกกา,kʰwɔːk̚˥˩.kaː˧,1
1886,ควอล,kʰwɔːl˧,1
1894,ควาญช้าง,kʰwaːn˧.t͡ɕʰaːŋ˦˥,1
2515,งานวิจัย,ŋaːn˧.wi˦˥.t͡ɕaj˧,1
2749,จีฮัด,t͡ɕiː˧.hat̚˦˥,1
2763,จุดศูนย์กลาง,t͡ɕut̚˨˩.suːn˩˩˦.klaːŋ˧,1
2764,จุดศูนย์ถ่วง,t͡ɕut̚˨˩.suːn˩˩˦.tʰua̯ŋ˨˩,1
2995,ชาวประมง,t͡ɕʰaːw˧.pra˨˩.moŋ˧,1
3313,ฑังส,tʰaŋ˧.saʔ˨˩,1
3409,ดาวนพเคราะห์,daːw˧.nop̚˦˥.pʰa˦˥.kʰrɔʔ˦˥,1
3901,ตู้เซฟ,tuː˥˩.sef˦˥,2
3902,ตู้เซฟ,tuː˥˩.sep̚˦˥,2
4751,นักแสดงพากย์,nak̚˦˥.sa˨˩.dɛːŋ˧.pʰaːk̚˥˩,1
5077,บ.ช.,bɔː˧.t͡ɕʰɔː˧,1
6042,ผักกาด,pʰak̚˨˩.kaːt̚˨˩,1
6832,ภาษาจีนกลาง,pʰaː˧.saː˩˩˦.t͡ɕiːn˧.klaːŋ˧,1
6920,มติชน,ma˦˥.ti˨˩.t͡ɕʰon˧,1
6923,มติโจร,ma˦˥.ti˨˩.t͡ɕoːn˧,1
7112,มัชชาร,mat̚˦˥.t͡ɕʰaː˧.raʔ˦˥,1
7974,รูปแปดด้าน,ruːp̚˥˩.pa˨˩.pɛːt̚˨˩.daːn˥˩,1
8171,ลาตเท,laːt̚˥˩.tʰeː˥˩,1
8306,ลูกบอล,luːk̚˥˩.bɔn˧,2
8307,ลูกบอล,luːk̚˥˩.bɔl˧,2
8562,วิกิตำรา,wi˦˥.ki˨˩.tam˧.raː˧,1
8689,ว่านหางจระเข้,waːn˥˩.haːŋ˩˩˦.t͡ɕɔː˧.ra˦˥.kʰeː˥˩,1
8735,ศังข์รัศมิ์,saŋ˩˩˦.kʰa˨˩.rat̚˦˥,1
8795,ศุข,suk̚˨˩,1
9018,สมุทฺท,sa˨˩.mut̚˨˩,1
9054,สรรพสินค้า,sap̚˨˩.pʰa˦˥.sin˩˩˦.kʰaː˦˥,1
9703,สเปเนียล,sa˨˩.peː˧.nia̯l˥˩,1
9747,ส้มโอ,som˥˩.ʔoː˧,1
9771,หญ้าม็อส,jaː˥˩.mɔt̚˦˥,1
10272,หินบะซอลต์,hin˩˩˦.ba˨˩.sɔːn˧,1
10408,องค์จาตุคามรามเทพ,ʔoŋ˧.t͡ɕaː˧.tu˨˩.kʰaːm˧.raːm˧.ma˦˥.tʰeːp̚˥˩,1
10636,อะไรวะ,ʔa˨˩.raj˧.waʔ˦˥,1
10795,อาติโช๊ค,ʔaː˧.ti˨˩.t͡ɕʰoːk̚˦˥,1
10910,อินดรี,ʔin˧.driː˧,1
11053,อุรค,ʔu˨˩.rok̚˦˥,1
11054,อุรณ,ʔu˨˩.ra˦˥.naʔ˦˥,1
11387,เครื่องจำหน่ายสินค้าอัตโนมัติ,kʰrɯa̯ŋ˥˩.t͡ɕam˧.naːj˨˩.sin˩˩˦.kʰaː˦˥.ʔat̚˨˩.t...,1
11388,เครื่องจำหน่ายสินค้าแบบหยอดเหรียญ,kʰrɯa̯ŋ˥˩.t͡ɕam˧.naːj˨˩.sin˩˩˦.kʰaː˦˥.bɛːp̚˨˩....,1
11444,เครื่องแต่งกาย,kʰrɯa̯ŋ˥˩.tɛŋ˨˩.kaːj˧,1
11732,เดดสะมอเร่,deːt̚˦˥.sa˨˩.mɔː˧.reː˥˩,1
11905,เทิง,tʰɤːŋ˧,1
13661,โช้ค,t͡ɕʰoːk̚˦˥,1
13955,โสฒิ,soːt̚˨˩,1
14005,โอลิงกีโต,ʔoː˧.liŋ˧.kiː˧.toː˧,1

In [22]:
th_pron = pd.concat([wikipron, g2p])
th_pron = th_pron.drop(columns=['count'])
th_pron = th_pron.drop_duplicates(subset=['writing', 'phonetic']).sort_values(by='writing').reset_index(drop=True)
th_pron['count'] = th_pron['writing'].map(th_pron['writing'].value_counts())
th_pron

         writing            phonetic  count
0              ก                kɔː˧      2
1              ก          kɔː˧.kaj˨˩      2
2             ก.                kɔː˧      1
3           ก.ค.          kɔː˧.kʰɔː˧      1
4         ก.ท.ม.     kɔː˧.tʰɔː˧.mɔː˧      1
...          ...                 ...    ...
18532   ไฮโดรเจน  haj˧.droː˧.t͡ɕen˥˩      2
18533   ไฮโดรเจน  haj˧.droː˧.t͡ɕeːn˧      2
18534        ไฮ้               haj˦˥      1
18535  …ใด…หนึ่ง      ….daj˧.….nɯŋ˨˩      1
18536     …ไป…ไป       ….paj˧.….paj˧      1

[18537 rows x 3 columns]

In [36]:
th_pron.to_csv('th_pron.csv', index=False)

Match with RID

In [41]:
rid = pd.read_csv('rid_basic.csv')
rid['word_norm'] = rid['word'].str.replace(r'\s+[๐-๙]+$', '', regex=True)
rid

,word,meaning,children,parent,related,images,literature,word_norm
0,ก,[กอ] พยัญชนะตัวที่ ๑ เรียกว่า กอ ไก่ เป็นอักษ...,"ก กา, ก ข, ก ข ไม่กระดิกหู, ก หัน",NaN,NaN,NaN,NaN,ก
1,ก กา,น. เรียกแม่บทแจกลูกพยัญชนะต้นกับสระโดยไม่มีตัว...,NaN,ก,NaN,NaN,NaN,ก กา
2,ก ข,[กอข้อ] (โบ) น. พยัญชนะแต่ ก ถึง ฮ.,NaN,ก,NaN,NaN,NaN,ก ข
3,ก ข ไม่กระดิกหู,[กอข้อ-] (โบ) (สำ) น. ผู้ที่เรียนหนังสือแล้ว...,NaN,ก,NaN,NaN,NaN,ก ข ไม่กระดิกหู
4,ก หัน,น. อักษร ก คู่ ในหนังสือโบราณใช้แทนไม้หันอากาศ...,NaN,ก,NaN,NaN,NaN,ก หัน
...,...,...,...,...,...,...,...,...
43105,ไฮโดรเจนเพอร์ออกไซด์,[-โดฺร-] น. สารประกอบอนินทรีย์ชนิดหนึ่ง มีสูตร...,NaN,NaN,NaN,NaN,NaN,ไฮโดรเจนเพอร์ออกไซด์
43106,ไฮโดรมิเตอร์,[-โดฺร-] น. เครื่องมือสำหรับวัดความถ่วงจำเพาะข...,NaN,NaN,NaN,NaN,NaN,ไฮโดรมิเตอร์
43107,ไฮไฟ,น. ระบบขยายสัญญาณไฟฟ้าเพื่อเปลี่ยนเป็นคลื่นเสี...,NaN,NaN,NaN,NaN,NaN,ไฮไฟ
43108,ไฮโล,น. ชื่อการพนันชนิดหนึ่ง เล่นด้วยการทอดลูกเต๋า ...,NaN,NaN,NaN,NaN,NaN,ไฮโล
43109,ไฮฮี,**ดู ไกร ๑ และ ไทร** .,NaN,NaN,"ไกร ๑, ไทร",NaN,NaN,ไฮฮี

In [45]:
th_pron_missing = th_pron[~th_pron['writing'].isin(rid['word_norm'])]
th_pron_missing

            writing               phonetic  count
2                ก.                   kɔː˧      1
3              ก.ค.             kɔː˧.kʰɔː˧      1
4            ก.ท.ม.        kɔː˧.tʰɔː˧.mɔː˧      1
5              ก.พ.             kɔː˧.pʰɔː˧      1
6              ก.ย.              kɔː˧.jɔː˧      1
...             ...                    ...    ...
18528  ไฮเปอร์ลิงก์         haj˧.pɤː˧.liŋ˧      2
18529   ไฮเพอร์โบลา  haj˧.pʰɤː˧.boː˧.laː˥˩      1
18530          ไฮโซ              haj˧.soː˧      1
18535     …ใด…หนึ่ง         ….daj˧.….nɯŋ˨˩      1
18536        …ไป…ไป          ….paj˧.….paj˧      1

[8569 rows x 3 columns]

In [46]:
th_pron_missing[~th_pron_missing['phonetic'].str.contains('.', regex=False, na=False)]

      writing  phonetic  count
2          ก.      kɔː˧      1
40         กฏ    kot̚˨˩      1
114      กรรม      kam˧      2
398      กรีก  kriːk̚˨˩      1
399      กรีซ   kriːs˦˥      2
...       ...       ...    ...
18274     ไฝ่     faj˨˩      1
18303    ไฟล์     faːj˧      1
18309      ไม      maj˧      1
18429      ไว      waj˧      1
18449     ไสย    saj˩˩˦      2

[707 rows x 3 columns]

In [50]:
th_pron_missing[~th_pron_missing['phonetic'].str.contains('.', regex=False, na=False)].sample(10)

      writing   phonetic  count
16642    แฃวน  kʰwɛːn˩˩˦      1
2780     ควีน    kʰwiːn˧      1
8282    พอร์ต    pʰɔt̚˨˩      2
6485     บรรณ       ban˧      2
6683      บัส     bat̚˦˥      2
15791  เยี่ยง    jia̯ŋ˥˩      1
15696    เมรุ      meːn˧      3
3575      จูล    t͡ɕuːn˧      1
17601    โบว์       boː˧      1
15307   เนิ่น     nɤːn˥˩      1